@extends('admin.layout')
@php $labels=['service'=>['الخدمات','الخدمة'],'project'=>['المشاريع','المشروع'],'equipment'=>['المعدات','المعدة'],'team'=>['الفريق','عضو الفريق']]; [$plural,$singular]=$labels[$kind]; @endphp
@section('title',$plural)
@section('content')
<div class="admin-title"><div><h1>إدارة {{ $plural }}</h1><p class="text-secondary mb-0">إضافة وتعديل وترتيب وإظهار المحتوى المنشور.</p></div><a class="btn btn-outline-dark" href="{{ route('admin.media') }}">اختيار أو رفع صورة</a></div>
<div class="admin-panel"><details><summary class="fw-bold">إضافة {{ $singular }} جديدة</summary><form class="mt-3" method="post" action="{{ route('admin.catalog.store',$kind) }}" data-ajax-form data-reload="true">@csrf @include('admin.partials.item-fields',['item'=>null])<div class="form-feedback mt-3" data-form-feedback></div></form></details></div>
<section class="admin-panel"><h2>{{ $plural }} الحالية ({{ $items->count() }})</h2>@if($items->isEmpty())<div class="empty-state">لا يوجد محتوى هنا بعد.</div>@else<div class="section-editor-list">@foreach($items as $item)<details class="section-editor"><summary class="section-editor-head"><strong>{{ $item->title }}</strong><span class="badge-status {{ $item->is_published?'live':'' }}">{{ $item->is_published?'منشور':'مخفي' }}</span>@if($kind==='project'&&$item->is_demo)<span class="badge-status">تصوري</span>@endif</summary><div class="p-3"><form method="post" action="{{ route('admin.catalog.update',[$kind,$item->id]) }}" data-ajax-form data-reload="true">@csrf @method('PUT') @include('admin.partials.item-fields',['item'=>$item])<div class="form-feedback mt-3" data-form-feedback></div></form><form class="mt-2" method="post" action="{{ route('admin.catalog.delete',[$kind,$item->id]) }}" onsubmit="return confirm('حذف {{ $singular }}؟')">@csrf @method('DELETE')<button class="btn btn-outline-danger btn-sm">حذف {{ $singular }}</button></form>@if(($revisions[$item->id]??collect())->isNotEmpty())<details class="admin-panel mt-3"><summary>الإصدارات السابقة ({{ $revisions[$item->id]->count() }})</summary><p class="help-text mt-2">استعادة إصدار تحفظ المحتوى الحالي لإمكانية الرجوع إليه.</p><div class="table-wrap"><table class="admin-table"><thead><tr><th>التاريخ</th><th>العنوان السابق</th><th></th></tr></thead><tbody>@foreach($revisions[$item->id] as $revision)<tr><td>{{ $revision->created_at->format('Y-m-d H:i') }}</td><td>{{ $revision->version_data['title']??'' }}</td><td><form method="post" action="{{ route('admin.catalog.revisions.restore',[$kind,$item->id,$revision->id]) }}" onsubmit="return confirm('استعادة هذا الإصدار؟ سيتم حفظ المحتوى الحالي كإصدار أيضًا.')">@csrf<button class="btn btn-outline-dark btn-sm">استعادة</button></form></td></tr>@endforeach</tbody></table></div></details>@endif</div></details>@endforeach</div>@endif</section>
<script>window.siteMedia = @json($media->map(fn($m)=>['path'=>$m->path,'name'=>$m->original_name,'alt'=>$m->alt])->values());</script>
@endsection
