@extends('admin.layout')
@section('title','لوحة التحكم')
@section('content')
<div class="admin-title"><div><h1>مرحبًا {{ auth()->user()->name }}</h1><p class="text-secondary mb-0">ملخص حالة الموقع والمحتوى.</p></div><a class="btn btn-dark btn-sm" href="{{ route('home') }}" target="_blank" rel="noopener">فتح الموقع <i class="bi bi-box-arrow-up-left"></i></a></div>
<div class="admin-stats"><div class="admin-stat"><strong>{{ $pageCount }}</strong><span>صفحة</span></div><div class="admin-stat"><strong>{{ $itemCount }}</strong><span>خدمة ومشروع ومعدة وفريق</span></div><div class="admin-stat"><strong>{{ $newCount }}</strong><span>طلبات جديدة</span></div><div class="admin-stat"><strong>{{ $mediaCount }}</strong><span>ملف في مكتبة الوسائط</span></div></div>
<section class="admin-panel"><div class="d-flex justify-content-between align-items-center gap-3 flex-wrap"><div><h2>طلبات المقايسة الأخيرة</h2><p class="help-text">الطلبات محفوظة محليًا في قاعدة البيانات ولا ترسل بريدًا دون إعداد SMTP.</p></div><a class="btn btn-outline-dark btn-sm" href="{{ route('admin.leads') }}">عرض جميع الطلبات</a></div>
    @if($latest->isEmpty())<div class="empty-state">لا توجد طلبات حتى الآن.</div>@else<div class="table-wrap"><table class="admin-table"><thead><tr><th>الاسم</th><th>نوع المشروع</th><th>رقم واتساب</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>@foreach($latest as $lead)<tr><td>{{ $lead->name }}</td><td>{{ $lead->project_type }}</td><td>{{ $lead->whatsapp }}</td><td>{{ $lead->status }}</td><td>{{ $lead->created_at->format('Y-m-d H:i') }}</td></tr>@endforeach</tbody></table></div>@endif
</section>
<section class="admin-panel"><h2>إصدارات قاعدة البيانات والملفات</h2><p>النسخة تشمل SQLite ومكتبة الصور. احتفظ بها خارج الخادم. للاستعادة ارفعها من هذه الصفحة؛ ستُستبدل بيانات الموقع والوسائط الحالية بما في النسخة.</p>@if(auth()->user()->role==='manager')<div class="d-flex flex-wrap gap-3 align-items-end"><a class="btn btn-dark btn-sm" href="{{ route('admin.backup.download') }}">تنزيل نسخة احتياطية ZIP</a><form method="post" action="{{ route('admin.backup.restore') }}" enctype="multipart/form-data" onsubmit="return confirm('سيتم استبدال قاعدة بيانات ووسائط الموقع الحالية بالنسخة الاحتياطية. هل تريد المتابعة؟')">@csrf<div class="d-flex gap-2"><input class="form-control form-control-sm" type="file" name="backup" accept=".zip" required><button class="btn btn-outline-dark btn-sm" type="submit">استعادة</button></div></form></div>@else<p class="help-text">النسخ والاستعادة متاحة لحساب المدير فقط.</p>@endif</section>
<section class="admin-panel"><h2>آخر التغييرات</h2>@if($logs->isEmpty())<div class="empty-state">سيظهر سجل التغييرات هنا.</div>@else<div class="table-wrap"><table class="admin-table"><thead><tr><th>التغيير</th><th>المنفذ</th><th>التاريخ</th></tr></thead><tbody>@foreach($logs as $log)<tr><td>{{ $log->summary }}</td><td>{{ $log->user_id }}</td><td>{{ $log->created_at->format('Y-m-d H:i') }}</td></tr>@endforeach</tbody></table></div>@endif</section>
@endsection
