@extends('admin.layout')
@section('title','مكتبة الوسائط')
@section('content')
<div class="admin-title"><div><h1>مكتبة الوسائط</h1><p class="text-secondary mb-0">الصور محفوظة في التخزين الدائم، وتظهر للربط في الصفحات والخدمات والمشاريع.</p></div></div>
<section class="admin-panel"><h2>رفع صور جديدة</h2><form method="post" action="{{ route('admin.media.upload') }}" enctype="multipart/form-data"><div class="form-field mb-3"><label>اختر حتى 20 صورة (JPEG أو PNG أو WebP، حتى 8MB للصورة)</label><input class="form-control" type="file" name="files[]" accept="image/jpeg,image/png,image/webp" multiple required></div><div class="form-field mb-3"><label>نص بديل افتراضي للدفعة</label><input class="form-control" name="alt" maxlength="255"></div>@csrf<button class="btn btn-dark">رفع الصور</button></form><p class="help-text mt-2">يمكن تعديل النص البديل لكل صورة بعد الرفع. الصور الافتتاحية مأخوذة من مجلد photos.</p></section>
@if($errors->has('media'))<div class="form-errors">{{ $errors->first('media') }}</div>@endif
<section class="admin-panel"><h2>الملفات ({{ $media->total() }})</h2>@if($media->isEmpty())<div class="empty-state">مكتبة الوسائط فارغة.</div>@else<div class="media-grid">@foreach($media as $asset)<article class="media-card"><img src="{{ asset('storage/'.ltrim($asset->path,'/')) }}" alt="{{ $asset->alt ?: $asset->original_name }}"><small>{{ $asset->original_name }} · {{ number_format($asset->size/1024,0) }}KB</small><small dir="ltr">{{ $asset->path }}</small><form class="mt-2" method="post" action="{{ route('admin.media.update',$asset->id) }}" data-ajax-form data-reload="true">@csrf @method('PUT')<label class="form-label small">النص البديل بالعربية</label><input class="form-control form-control-sm mb-2" name="alt" value="{{ $asset->alt }}" maxlength="255"><label class="form-label small">النص البديل بالإنجليزية</label><input class="form-control form-control-sm mb-2" name="alt_en" dir="ltr" value="{{ $asset->translations['en']['alt'] ?? '' }}" maxlength="255"><button class="btn btn-outline-dark btn-sm">حفظ النص البديل</button><div class="form-feedback" data-form-feedback></div></form><form class="mt-2" method="post" action="{{ route('admin.media.delete',$asset->id) }}" onsubmit="return confirm('حذف هذه الصورة نهائيًا من المكتبة؟')">@csrf @method('DELETE')<button class="btn btn-outline-danger btn-sm">حذف</button></form></article>@endforeach</div>@endif</section>
<div class="pager">{{ $media->links('pagination::bootstrap-5') }}</div>
@endsection
