@extends('admin.layout')
@section('title','إعدادات الموقع')
@section('content')
@php $english = $general['translations']['en'] ?? []; @endphp
<div class="admin-title"><div><h1>الهوية وإعدادات الموقع</h1><p class="text-secondary mb-0">تعدّل هذه الحقول الهيدر والفوتر والألوان والتواصل مباشرة.</p></div><a class="btn btn-outline-dark" href="{{ route('admin.media') }}">إدارة الصور والشعار</a></div>
<form method="post" action="{{ route('admin.settings.update') }}" data-ajax-form data-reload="true">@csrf @method('PUT')
<section class="admin-panel"><h2>العلامة التجارية والتواصل</h2><div class="input-group-admin">
    <div class="form-field"><label>اسم الشركة</label><input class="form-control" name="company_name" required value="{{ old('company_name',$general['company_name']??'') }}"></div><div class="form-field"><label>الشعار النصي القصير</label><input class="form-control" name="tagline" value="{{ old('tagline',$general['tagline']??'') }}"></div>
    <div class="form-field"><label>رقم الهاتف</label><input class="form-control" name="phone" dir="ltr" value="{{ old('phone',$general['phone']??'') }}" placeholder="010xxxxxxxx (غير قابل للاتصال)"></div><div class="form-field"><label>رقم واتساب الدولي</label><input class="form-control" name="whatsapp" dir="ltr" value="{{ old('whatsapp',$general['whatsapp']??'') }}" placeholder="مثال: 201012345678"><small class="help-text">لن يُفعّل رابط واتساب حتى إدخال 10–15 رقمًا صالحًا.</small></div>
    <div class="form-field"><label>البريد الإلكتروني</label><input class="form-control" name="email" type="email" value="{{ old('email',$general['email']??'') }}"></div><div class="form-field"><label>العنوان</label><input class="form-control" name="address" value="{{ old('address',$general['address']??'') }}"></div>
    <div class="form-field"><label>ملف الشعار في مكتبة الوسائط</label><select class="form-control" name="logo"><option value="">شعار نصي افتراضي</option>@foreach($media as $asset)<option value="{{ $asset->path }}" @selected(old('logo',$general['logo']??'')===$asset->path)>{{ $asset->alt ?: $asset->original_name }}</option>@endforeach</select></div><div class="form-field"><label>أيقونة الموقع</label><select class="form-control" name="favicon"><option value="">بدون أيقونة مخصصة</option>@foreach($media as $asset)<option value="{{ $asset->path }}" @selected(old('favicon',$general['favicon']??'')===$asset->path)>{{ $asset->alt ?: $asset->original_name }}</option>@endforeach</select></div>
</div></section>
<section class="admin-panel"><h2>محتوى الموقع بالإنجليزية</h2><p class="help-text">الحقول الاختيارية أدناه تظهر عند اختيار English. اترك أي حقل فارغًا لاستخدام النص العربي كبديل.</p><div class="input-group-admin">
    <div class="form-field"><label>اسم الشركة</label><input class="form-control" name="company_name_en" dir="ltr" value="{{ old('company_name_en',$english['company_name']??'') }}"></div><div class="form-field"><label>الشعار النصي القصير</label><input class="form-control" name="tagline_en" dir="ltr" value="{{ old('tagline_en',$english['tagline']??'') }}"></div>
    <div class="form-field"><label>العنوان</label><input class="form-control" name="address_en" dir="ltr" value="{{ old('address_en',$english['address']??'') }}"></div><div class="form-field"><label>نص زر الهيدر</label><input class="form-control" name="header_cta_label_en" dir="ltr" value="{{ old('header_cta_label_en',$english['header_cta_label']??'') }}"></div>
</div>
<div class="form-field mt-3"><label>روابط القائمة الرئيسية الإنجليزية (سطر لكل رابط: الاسم|المسار)</label><textarea class="form-control" name="nav_text_en" dir="ltr" rows="6">{{ old('nav_text_en',collect($english['nav']??[])->map(fn($link)=>($link['label']??'').'|'.($link['url']??''))->implode("\n")) }}</textarea></div>
<div class="form-field mt-3"><label>روابط الفوتر الإنجليزية (سطر لكل رابط: الاسم|المسار)</label><textarea class="form-control" name="footer_nav_text_en" dir="ltr" rows="5">{{ old('footer_nav_text_en',collect($english['footer_nav']??[])->map(fn($link)=>($link['label']??'').'|'.($link['url']??''))->implode("\n")) }}</textarea></div>
<div class="form-field mt-3"><label>وصف الفوتر</label><textarea class="form-control" name="footer_note_en" dir="ltr">{{ old('footer_note_en',$english['footer_note']??'') }}</textarea></div></section>
<section class="admin-panel"><h2>المظهر</h2><div class="input-group-admin"><div class="form-field"><label>اللون الأساسي</label><input class="form-control form-control-color" type="color" name="primary_color" value="{{ old('primary_color',$general['primary_color']??'#102332') }}"></div><div class="form-field"><label>اللون الذهبي</label><input class="form-control form-control-color" type="color" name="accent_color" value="{{ old('accent_color',$general['accent_color']??'#c59d5f') }}"></div><div class="form-field"><label>الخط العربي</label><select class="form-control" name="font">@foreach(['Cairo','Tajawal','IBM Plex Sans Arabic'] as $font)<option @selected(old('font',$general['font']??'Cairo')===$font)>{{ $font }}</option>@endforeach</select></div></div></section>
<section class="admin-panel"><h2>قائمة الموقع والفوتر</h2><div class="form-field"><label>روابط القائمة الرئيسية (سطر لكل رابط: الاسم|المسار)</label><textarea class="form-control" name="nav_text" dir="rtl" rows="8">{{ old('nav_text',collect($general['nav']??[])->map(fn($link)=>($link['label']??'').'|'.($link['url']??''))->implode("\n")) }}</textarea><small class="help-text">لرابط داخلي اكتب /about مثلًا. تقبل القائمة أيضًا رابط HTTPS خارجي.</small></div><div class="form-field mt-3"><label>زر الهيدر — الاسم والرابط</label><div class="input-group-admin"><input class="form-control" name="header_cta_label" value="{{ old('header_cta_label',$general['header_cta_label']??'مقايسة مجانية') }}" maxlength="100"><input class="form-control" name="header_cta_url" dir="ltr" value="{{ old('header_cta_url',$general['header_cta_url']??'/contact') }}" maxlength="255"></div></div><div class="form-field mt-3"><label>روابط الفوتر (سطر لكل رابط: الاسم|المسار)</label><textarea class="form-control" name="footer_nav_text" dir="rtl" rows="6">{{ old('footer_nav_text',collect($general['footer_nav']??[])->map(fn($link)=>($link['label']??'').'|'.($link['url']??''))->implode("\n")) }}</textarea></div><div class="form-field mt-3"><label>وصف الفوتر</label><textarea class="form-control" name="footer_note">{{ old('footer_note',$general['footer_note']??'') }}</textarea></div></section>
<section class="admin-panel"><h2>روابط التواصل والتنبيهات</h2><div class="input-group-admin"><div class="form-field"><label>Facebook</label><input class="form-control" name="facebook" type="url" dir="ltr" value="{{ old('facebook',$general['facebook']??'') }}"></div><div class="form-field"><label>Instagram</label><input class="form-control" name="instagram" type="url" dir="ltr" value="{{ old('instagram',$general['instagram']??'') }}"></div><div class="form-field"><label>LinkedIn</label><input class="form-control" name="linkedin" type="url" dir="ltr" value="{{ old('linkedin',$general['linkedin']??'') }}"></div><div class="form-field"><label><input type="checkbox" name="show_demo_notice" value="1" @checked(old('show_demo_notice',$general['show_demo_notice']??true))> إظهار تنويه النماذج التصورية</label></div></div></section>
<button class="btn btn-dark" type="submit">حفظ إعدادات الموقع</button><div class="form-feedback mt-3" data-form-feedback role="status"></div>
</form>
<script>window.siteMedia = @json($media->map(fn($m)=>['path'=>$m->path,'name'=>$m->original_name,'alt'=>$m->alt])->values());</script>
@endsection
