@php
    $type = $s['type'] ?? '';
    $path = $s['image'] ?? '';
    $imageUrl = $path ? (str_starts_with($path, 'https://') ? $path : asset('storage/'.ltrim($path, '/'))) : '';
    $sectionClass = 'section '.(($s['background'] ?? '') === 'sand' ? 'sand' : (($s['background'] ?? '') === 'navy' ? 'navy' : '')).' '.(($s['spacing'] ?? '') === 'compact' ? 'compact' : (($s['spacing'] ?? '') === 'spacious' ? 'spacious' : ''));
    $items = $s['items'] ?? [];
@endphp
@if($type === 'hero')
    @if(!empty($s['image_has_text']) && $imageUrl)
        <section class="hero-brand" aria-labelledby="home-title"><h1 id="home-title" class="visually-hidden">{{ $s['title'] ?? '' }}</h1><img class="hero-brand-image" src="{{ $imageUrl }}" alt="{{ $s['alt'] ?? __('بانر شركة الزهراء للمقاولات والتشييد والبناء') }}"><div class="hero-brand-actions"><div class="container"><p>{{ $s['text'] ?? '' }}</p><div class="hero-actions"><a class="btn btn-gold" href="{{ \App\Support\SiteUrl::path($s['primary_url'] ?? '/contact') }}">{{ $s['primary_label'] ?? __('احصل على مقايسة مجانية') }} <i class="bi bi-arrow-left"></i></a><a class="btn btn-outline-dark" href="{{ \App\Support\SiteUrl::path($s['secondary_url'] ?? '/projects') }}">{{ $s['secondary_label'] ?? __('شاهد مشاريعنا') }}</a></div></div></div></section>
    @else
        <section class="hero" style="background-image:url('{{ $imageUrl }}')"><div class="container hero-inner"><span class="eyebrow">{{ __('خبرة هندسية تثق بها') }}</span><h1>{{ $s['title'] ?? '' }}</h1><p>{{ $s['text'] ?? '' }}</p><div class="hero-actions"><a class="btn btn-gold" href="{{ \App\Support\SiteUrl::path($s['primary_url'] ?? '/contact') }}">{{ $s['primary_label'] ?? __('احصل على مقايسة مجانية') }} <i class="bi bi-arrow-left"></i></a><a class="btn btn-outline-light" href="{{ \App\Support\SiteUrl::path($s['secondary_url'] ?? '/projects') }}">{{ $s['secondary_label'] ?? __('شاهد مشاريعنا') }}</a></div></div></section>
    @endif
@elseif($type === 'page-hero')
    <section class="page-hero" style="--hero-image:url('{{ $imageUrl }}')"><div class="container"><span class="eyebrow">{{ __('شركة الزهراء للمقاولات') }}</span><h1>{{ $s['title'] ?? '' }}</h1><p>{{ $s['text'] ?? '' }}</p></div></section>
@elseif($type === 'stats')
    <section class="stats-band"><div class="container stats-grid" style="--section-cols:{{ max(1,min(4,(int)($s['columns'] ?? 4))) }}">@foreach($items as $item)<div class="stat"><strong>{{ $item['value'] ?? '' }}</strong><span>{{ $item['label'] ?? '' }}</span></div>@endforeach</div></section>
@elseif($type === 'text-image')
    <section class="{{ $sectionClass }}"><div class="container split {{ ($s['align'] ?? 'right') === 'left' ? 'reverse' : '' }}"><div class="split-image"><img loading="lazy" src="{{ $imageUrl }}" alt="{{ $s['alt'] ?? $s['title'] ?? '' }}"></div><div class="split-copy align-{{ $s['align'] ?? 'right' }}"><span class="eyebrow">{{ __('من نحن') }}</span><h2>{{ $s['title'] ?? '' }}</h2><p>{{ $s['text'] ?? '' }}</p>@if(!empty($s['link_label']))<a class="text-link" href="{{ \App\Support\SiteUrl::path($s['link_url'] ?? '/about') }}">{{ $s['link_label'] }} ←</a>@endif</div></div></section>
@elseif(in_array($type, ['services','projects','team','equipment'], true))
    @php $collection = $type === 'services' ? $services : ($type === 'projects' ? $projects : ($type === 'team' ? $team : $equipment)); @endphp
    <section class="{{ $sectionClass }}"><div class="container">
        <div class="section-heading align-{{ $s['align'] ?? 'center' }}"><span class="eyebrow">{{ $type === 'services' ? __('ما نقدمه') : ($type === 'projects' ? __('نماذج أعمال') : ($type === 'team' ? __('خبراتنا') : __('أسطول الشركة'))) }}</span><h2>{{ $s['title'] ?? '' }}</h2><p>{{ $s['text'] ?? '' }}</p></div>
        @if($type === 'projects')<div class="filters"><button class="filter-button active" type="button" data-project-filter="all">{{ __('الكل') }}</button>@foreach($collection->pluck('category')->filter()->unique() as $category)<button class="filter-button" type="button" data-project-filter="{{ $category }}">{{ $category }}</button>@endforeach</div>@endif
        @if($collection->isEmpty())<div class="empty-state">{{ __('سيتم إضافة المحتوى قريبًا.') }}</div>@else<div class="cards" style="--section-cols:{{ max(1,min(4,(int)($s['columns'] ?? 3))) }}">@foreach($collection as $item)<article class="card" data-filter-card data-category="{{ $item->category }}">
            <div class="card-image">@if($type === 'projects' && $item->is_demo)<span class="demo-badge">{{ __('نموذج تصوري') }}</span>@endif<img loading="lazy" src="{{ asset('storage/'.ltrim($item->image ?? 'site/1.jpeg','/')) }}" alt="{{ $item->alt ?: $item->title }}"></div>
            <div class="card-body">@if($type === 'projects')<div class="project-meta"><span>{{ $item->location }}</span><span>{{ $item->project_year }}</span>@if($item->area)<span>{{ number_format($item->area) }} {{ __('م²') }}</span>@endif</div>@elseif($type === 'equipment')<span class="type-label">{{ $item->quantity }}</span>@elseif($type === 'team')<span class="type-label">{{ $item->quantity }}</span>@else<span class="type-label">{{ __('خدمات هندسية') }}</span>@endif
                <h3>{{ $item->title }}</h3><p>{{ $item->description }}</p>
                @if($type === 'services')<a class="text-link" href="{{ \App\Support\SiteUrl::route('services.show', $item->slug) }}">{{ __('تفاصيل الخدمة') }} ←</a>@elseif($type === 'projects')<a class="text-link" href="{{ \App\Support\SiteUrl::route('projects.show', $item->slug) }}">{{ __('تفاصيل النموذج') }} ←</a>@endif
            </div></article>@endforeach</div>@endif
        @if($type === 'services')<div class="text-center mt-4"><a class="btn btn-outline-dark" href="{{ \App\Support\SiteUrl::route('services') }}">{{ __('اكتشف كل الخدمات') }}</a></div>@elseif($type === 'projects')<div class="text-center mt-4"><a class="btn btn-outline-dark" href="{{ \App\Support\SiteUrl::route('projects') }}">{{ __('جميع النماذج') }}</a></div>@endif
    </div></section>
@elseif($type === 'process')
    <section class="{{ $sectionClass }}"><div class="container"><div class="section-heading align-{{ $s['align'] ?? 'center' }}"><span class="eyebrow">{{ __('خطوات مدروسة') }}</span><h2>{{ $s['title'] ?? '' }}</h2><p>{{ $s['text'] ?? '' }}</p></div><div class="steps-grid" style="--section-cols:{{ max(1,min(4,(int)($s['columns'] ?? 4))) }}">@foreach($items as $item)<article class="step"><span class="step-number">{{ $item['value'] ?? sprintf('%02d',$loop->iteration) }}</span><h3>{{ $item['label'] ?? $item['title'] ?? '' }}</h3></article>@endforeach</div></div></section>
@elseif($type === 'features')
    <section class="{{ $sectionClass }}"><div class="container"><div class="section-heading align-{{ $s['align'] ?? 'center' }}"><span class="eyebrow">{{ __('قيمة مضافة في كل مرحلة') }}</span><h2>{{ $s['title'] ?? '' }}</h2><p>{{ $s['text'] ?? '' }}</p></div><div class="features-grid" style="--section-cols:{{ max(1,min(4,(int)($s['columns'] ?? 3))) }}">@foreach($items as $item)<div class="feature"><span class="feature-mark"><i class="bi bi-check2"></i></span>{{ $item['label'] ?? $item['title'] ?? '' }}</div>@endforeach</div></div></section>
@elseif($type === 'before-after')
    <section class="{{ $sectionClass }}"><div class="container"><div class="section-heading align-{{ $s['align'] ?? 'center' }}"><span class="eyebrow">{{ __('من الفكرة إلى الواقع') }}</span><h2>{{ $s['title'] ?? '' }}</h2><p>{{ $s['text'] ?? '' }}</p></div><figure class="before-after"><img loading="lazy" src="{{ $imageUrl }}" alt="{{ $s['alt'] ?? __('صورة مركبة توضيحية قبل وبعد تحويل أرض إلى فيلا') }}"><figcaption>{{ __('صورة مقارنة مركبة للتوضيح، وليست تسجيلًا لمشروع موثق. يمكن استبدالها بصورتين للموقع نفسه من لوحة الإدارة.') }}</figcaption></figure></div></section>
@elseif($type === 'values')
    <section class="{{ $sectionClass }}"><div class="container"><div class="section-heading align-{{ $s['align'] ?? 'center' }}"><span class="eyebrow">{{ __('مبادئنا') }}</span><h2>{{ $s['title'] ?? '' }}</h2><p>{{ $s['text'] ?? '' }}</p></div><div class="values-grid" style="--section-cols:{{ max(1,min(4,(int)($s['columns'] ?? 3))) }}">@foreach($items as $item)<article class="value-card"><h3>{{ $item['title'] ?? '' }}</h3><p>{{ $item['text'] ?? '' }}</p></article>@endforeach</div></div></section>
@elseif($type === 'gallery')
    <section class="{{ $sectionClass }}"><div class="container"><div class="section-heading align-{{ $s['align'] ?? 'center' }}"><span class="eyebrow">{{ __('من مواقع التنفيذ') }}</span><h2>{{ $s['title'] ?? '' }}</h2><p>{{ $s['text'] ?? '' }}</p></div><div class="gallery-grid">@foreach(($s['images'] ?? []) as $galleryImage)<img loading="lazy" src="{{ asset('storage/'.ltrim($galleryImage,'/')) }}" alt="{{ $s['title'] ?? __('صورة أعمال الشركة') }}">@endforeach</div></div></section>
@elseif($type === 'cta')
    <section class="{{ $sectionClass }}"><div class="container"><div class="cta-panel"><div><h2>{{ $s['title'] ?? '' }}</h2><p>{{ $s['text'] ?? '' }}</p></div><a class="btn btn-gold" href="{{ \App\Support\SiteUrl::path($s['primary_url'] ?? '/contact') }}">{{ $s['primary_label'] ?? __('اطلب مقايسة مجانية') }} <i class="bi bi-arrow-left"></i></a></div></div></section>
@elseif($type === 'contact')
    @php $waDigits = preg_replace('/\D+/', '', (string)($settings['whatsapp'] ?? '')); $validWhatsApp = strlen($waDigits) >= 10 && strlen($waDigits) <= 15; @endphp
    <section class="{{ $sectionClass }}"><div class="container"><div class="section-heading align-{{ $s['align'] ?? 'center' }}"><span class="eyebrow">{{ __('نبدأ من هنا') }}</span><h2>{{ $s['title'] ?? __('اطلب مقايسة مجانية') }}</h2><p>{{ $s['text'] ?? '' }}</p></div><div class="contact-layout">
        <div class="contact-info"><h2>{{ __('يسعدنا التواصل معك') }}</h2><div class="contact-row"><strong>{{ __('الموقع') }}</strong>{{ $settings['address'] ?? __('القاهرة الجديدة، مصر') }}</div><div class="contact-row"><strong>{{ __('البريد الإلكتروني') }}</strong><a href="mailto:{{ $settings['email'] ?? 'info@alzahraa.construction' }}">{{ $settings['email'] ?? 'info@alzahraa.construction' }}</a></div><div class="contact-row"><strong>{{ __('الهاتف') }}</strong>@php $digits=preg_replace('/\D+/', '', (string)($settings['phone'] ?? '')); @endphp @if(strlen($digits)>=8 && strlen($digits)<=15 && !str_contains((string)($settings['phone'] ?? ''),'x'))<a href="tel:{{ $digits }}">{{ $settings['phone'] }}</a>@else{{ $settings['phone'] ?? __('يُرجى إرسال طلب المقايسة وسنتواصل معك.') }}@endif</div>@if($validWhatsApp)<a class="btn btn-gold mt-3" href="https://wa.me/{{ $waDigits }}" target="_blank" rel="noopener noreferrer">{{ __('مراسلتنا عبر واتساب') }}</a>@endif</div>
        <form class="estimate-form" method="post" action="{{ \App\Support\SiteUrl::route('estimate.store') }}">@csrf
            @if(session('estimate_success'))<div class="form-success" role="status">{{ __('شكرًا لك، تم حفظ طلب المقايسة بنجاح وسنتواصل معك.') }}</div>@endif
            @if($errors->any())<div class="form-errors" role="alert">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
            <div class="visually-hidden-field" aria-hidden="true"><label for="company_website">{{ __('لا تملأ هذا الحقل') }}</label><input id="company_website" name="company_website" tabindex="-1" autocomplete="off"></div>
            <div class="form-grid"><div class="form-field"><label for="name">{{ __('الاسم') }}</label><input class="form-control" id="name" name="name" value="{{ old('name') }}" required maxlength="120" autocomplete="name"></div><div class="form-field"><label for="whatsapp">{{ __('رقم الواتساب') }}</label><input class="form-control" id="whatsapp" name="whatsapp" value="{{ old('whatsapp') }}" required maxlength="40" inputmode="tel" autocomplete="tel" placeholder="{{ __('مثال: 01012345678') }}"></div><div class="form-field"><label for="project_type">{{ __('نوع المشروع') }}</label><select class="form-control" id="project_type" name="project_type" required><option value="">{{ __('اختر نوع المشروع') }}</option>@foreach(['villa'=>'فيلا','building'=>'عمارة','factory'=>'مصنع','finishing'=>'تشطيب','other'=>'أخرى'] as $key=>$label)<option value="{{ $key }}" @selected(old('project_type')===$key)>{{ __($label) }}</option>@endforeach</select></div><div class="form-field"><label for="area">{{ __('المساحة (م²)') }}</label><input class="form-control" id="area" name="area" value="{{ old('area') }}" maxlength="80" inputmode="decimal" placeholder="{{ __('إن توفرت') }}"></div><div class="form-field full"><label for="message">{{ __('رسالتك وتفاصيل المشروع') }}</label><textarea class="form-control" id="message" name="message" required minlength="5" maxlength="3000">{{ old('message') }}</textarea></div><div class="form-field full"><button class="btn btn-dark" type="submit">{{ __('إرسال طلب المقايسة') }} <i class="bi bi-arrow-left"></i></button><small class="help-text">{{ __('سيُحفظ طلبك في النظام، ولا تُرسل إشعارات بريدية ما لم تُضبط خدمة البريد.') }}</small></div></div>
        </form></div></div></section>
@endif
