@php $item=$item ?? null; $english=$item?->translations['en'] ?? []; @endphp
<div class="input-group-admin">
    <div class="form-field"><label>الاسم / العنوان</label><input class="form-control" name="title" value="{{ old('title',$item->title ?? '') }}" required maxlength="180"></div>
    <div class="form-field"><label>الرابط المختصر</label><input class="form-control" name="slug" dir="ltr" value="{{ old('slug',$item->slug ?? '') }}" maxlength="180"><small class="help-text">اتركه فارغًا إذا لم يحتج العنصر إلى صفحة تفاصيل.</small></div>
    @if(in_array($kind,['service','project']))<div class="form-field"><label>التصنيف</label><input class="form-control" name="category" value="{{ old('category',$item->category ?? '') }}" maxlength="100"></div>@endif
    @if($kind==='project')<div class="form-field"><label>الموقع</label><input class="form-control" name="location" value="{{ old('location',$item->location ?? '') }}"></div><div class="form-field"><label>السنة</label><input class="form-control" type="number" name="project_year" min="1950" max="2100" value="{{ old('project_year',$item->project_year ?? '') }}"></div><div class="form-field"><label>المساحة م²</label><input class="form-control" type="number" name="area" min="0" value="{{ old('area',$item->area ?? '') }}"></div>@endif
    @if(in_array($kind,['equipment','team']))<div class="form-field"><label>العدد / الوصف المختصر</label><input class="form-control" name="quantity" value="{{ old('quantity',$item->quantity ?? '') }}"></div>@endif
    <div class="form-field"><label>الصورة</label><select class="form-control" name="image"><option value="">بدون صورة</option>@foreach($media as $asset)<option value="{{ $asset->path }}" @selected(old('image',$item->image ?? '')===$asset->path)>{{ $asset->alt ?: $asset->original_name }}</option>@endforeach</select></div>
    <div class="form-field"><label>النص البديل للصورة</label><input class="form-control" name="alt" value="{{ old('alt',$item->alt ?? '') }}" maxlength="255"></div>
    <div class="form-field full"><label>وصف مختصر</label><textarea class="form-control" name="description" maxlength="1200">{{ old('description',$item->description ?? '') }}</textarea></div>
    @if(in_array($kind,['service','project']))<div class="form-field full"><label>التفاصيل</label><textarea class="form-control" name="body" maxlength="10000">{{ old('body',$item->body ?? '') }}</textarea></div>@endif
    <div class="form-field full"><details class="admin-translation-fields"><summary>الترجمة الإنجليزية (اختيارية)</summary><div class="input-group-admin mt-3">
        <div class="form-field"><label>الاسم / العنوان بالإنجليزية</label><input class="form-control" name="title_en" dir="ltr" value="{{ old('title_en',$english['title']??'') }}" maxlength="180"></div>
        @if(in_array($kind,['service','project']))<div class="form-field"><label>التصنيف بالإنجليزية</label><input class="form-control" name="category_en" dir="ltr" value="{{ old('category_en',$english['category']??'') }}" maxlength="100"></div>@endif
        @if($kind==='project')<div class="form-field"><label>الموقع بالإنجليزية</label><input class="form-control" name="location_en" dir="ltr" value="{{ old('location_en',$english['location']??'') }}"></div>@endif
        @if(in_array($kind,['equipment','team']))<div class="form-field"><label>العدد / الوصف المختصر بالإنجليزية</label><input class="form-control" name="quantity_en" dir="ltr" value="{{ old('quantity_en',$english['quantity']??'') }}"></div>@endif
        <div class="form-field"><label>النص البديل للصورة بالإنجليزية</label><input class="form-control" name="alt_en" dir="ltr" value="{{ old('alt_en',$english['alt']??'') }}" maxlength="255"></div>
        <div class="form-field full"><label>وصف مختصر بالإنجليزية</label><textarea class="form-control" name="description_en" dir="ltr" maxlength="1200">{{ old('description_en',$english['description']??'') }}</textarea></div>
        @if(in_array($kind,['service','project']))<div class="form-field full"><label>التفاصيل بالإنجليزية</label><textarea class="form-control" name="body_en" dir="ltr" maxlength="10000">{{ old('body_en',$english['body']??'') }}</textarea></div>@endif
    </div></details></div>
    @if($kind==='project')@php $selectedGallery=old('gallery',$item?->data['gallery'] ?? []); @endphp<div class="form-field full"><label>معرض صور المشروع</label><div class="section-checkboxes">@foreach($media as $asset)<label><input type="checkbox" name="gallery[]" value="{{ $asset->path }}" @checked(in_array($asset->path,$selectedGallery,true))> {{ $asset->alt ?: $asset->original_name }}</label>@endforeach</div><small class="help-text">اختر الصور التي تظهر في صفحة تفاصيل المشروع. ارفع الصور أولًا من مكتبة الوسائط.</small></div>@endif
    <div class="form-field"><label>ترتيب العرض</label><input class="form-control" type="number" name="sort_order" min="0" value="{{ old('sort_order',$item->sort_order ?? 0) }}"></div>
    <div class="form-field d-flex align-items-center gap-3 flex-wrap"><label class="d-flex align-items-center gap-2"><input type="checkbox" name="is_published" value="1" @checked(old('is_published',$item?->is_published ?? true))> منشور</label>@if($kind==='project')<label class="d-flex align-items-center gap-2"><input type="checkbox" name="is_demo" value="1" @checked(old('is_demo',$item?->is_demo ?? true))> مشروع تصوري تجريبي</label>@endif</div>
    @if(in_array($kind,['project','service']))<div class="form-field full"><label>بيانات إضافية بصيغة JSON (اختياري، مثل معرض الصور)</label><textarea class="form-control" name="data_json" dir="ltr" placeholder="{}">{{ old('data_json',json_encode($item?->data ?? new stdClass(),JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT)) }}</textarea></div>@endif
    <div class="full"><button class="btn btn-dark" type="submit">حفظ {{ $singular }}</button></div>
</div>
